language: node_js

node_js:
  - 9
cache:
  yarn: true
  directories:
    - ~/.npm
    - ~/.cache
    - node_modules

install:
  - yarn install

script:
  - yarn build

after_script:
  - cp build/index.html build/200.html
  - surge --project ./build --domain ls-react-sep-pr-$TRAVIS_PULL_REQUEST.surge.sh
